name = "sosth"
compatibility_date = "2024-03-25"

[build]
command = "npm run build"

[site]
bucket = "./public"
entry-point = "./src/worker.ts"

[env.production]
workers_dev = true
routes = [
  { pattern = "/*", zone_name = "uckarapong.workers.dev" }
]