name = "sosth"
compatibility_date = "2024-03-25"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "sosth-db"
database_id = "sosth-production"

[site]
bucket = ".next/standalone"